### ISSUE TITLE
Not compatible with Android 6.0

### ISSUE THREAD

**Issue by solooboroten** [Clam-/TraditionalT9#16] opened 2016-12-18 23:06 UTC
Hello.

It looks like this application is not compatible with Android 6.0. When installing on [SWELL N2](http://cnswell.com/en/product/product-more.asp?id=421), watch:
```
$ adb install TraditionalT9-git-e08c4a4.apk
58 KB/s (2504 bytes in 0.041s)
         pkg: /data/local/tmp/TraditionalT9-git-e08c4a4.apk
Error: java.lang.NullPointerException: Attempt to invoke virtual method 
'boolean java.lang.String.equals(java.lang.Object)' on a null object 
reference
```

PS: Play Market reports: This application is not compatible with your device. No carrier N2 N2.

**Comment by Clam-** [comment] 2016-12-19 11:58
Hi,

> Error: java.lang.NullPointerException: Attempt to invoke virtual method 
That's unfortunate. I'll fire up the emulator and see if I can reproduce the NPE when installing on Android 6.0.

> PS: Play Market reports: This application is not compatible with your device. No carrier N2 N2.
It's because the manufacturer has told Google Play Store that it doesn't "have" a 9KEY keypad (or QWERTY keypad).

The app on the marketplace requires a 9key keypad or qwerty keypad because it won't work on devices that don't have a dedicated hardware input mode. Unfortunately a number of manufacturers don't give Google Play correct information. I've tried to get Google to correct other devices, but they said they will only update details when the manufacturer informs them of corrections.

I'll check the first issue sometime later this week.

**Comment by Clam-** [comment] 2016-12-31 10:50
Hello again,

Sorry for the very long delay.
I install the Marshmallow (6.0) Google emulator image to test with:
```
>adb install build\outputs\apk\TraditionalT9-git-e08c4a4.apk
[100%] /data/local/tmp/TraditionalT9-git-e08c4a4.apk
        pkg: /data/local/tmp/TraditionalT9-git-e08c4a4.apk
Success
```

I am unsure what is wrong, but without more information I don't think I can investigate further. What does adb logcat output at the time of attempted installation?

**Comment by Clam-** [comment] 2017-04-22 12:56
Doesn't seem like this is an issue after all so I'll close it for now.
Feel free to respond if you are still having issues.

**Closed by Clam-** 2017-04-22 12:56 UTC
